name: serverpod_endpoint_versioning
description: A Serverpod utility for managing client-server compatibility. It integrates a client-side mechanism to ensure the client's version is compatible with the server.
version: 1.0.0
homepage: https://github.com/komossolutions/serverpod_endpoint_versioning

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  serverpod_client: ^2.9.2
  package_info_plus: ^9.0.0

dev_dependencies:
  lints: ^6.0.0
  flutter_lints: any
  test: ^1.25.0
